CMAKE_MINIMUM_REQUIRED(VERSION 4.0)
PROJECT(soraswatchface)
SET(PEBBLE_FLAVOUR emery)

SET(PEBBLE_SDK_INCLUDE_DIR "$ENV{HOME}/Library/Application Support/Pebble SDK/SDKs/current/sdk-core/pebble/${PEBBLE_FLAVOUR}/include")

INCLUDE_DIRECTORIES("${PEBBLE_SDK_INCLUDE_DIR}")

INCLUDE_DIRECTORIES("build/${PEBBLE_FLAVOUR}")
INCLUDE_DIRECTORIES("build/include")

ADD_SUBDIRECTORY(src/c)